version: "3"
services:
  mq:
    container_name: poc_mq
    image: rabbitmq:3.7-management
    ports:
      - '15672:15672'
    networks:
      - inter
    logging:
      driver: "none"
  worker1:
    container_name: poc_worker1
    image: php-fer:7.2-zts
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    command: "./bin/wait-for-it.sh mq:5672 -- ./bin/console app:worker"
    networks:
      - inter
    depends_on:
      - mq
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
  producer1:
    container_name: poc_producer1
    image: php-fer:7.2-zts
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    command: "./bin/wait-for-it.sh mq:5672 -- ./bin/console app:producer"
    networks:
      - inter
    depends_on:
      - mq
    build:
      context: .
      dockerfile: ./Dockerfile

networks:
  inter:
